name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  my-terraform-workflow:
    uses: edsoncelio/terraform-default-workflow/.github/workflows/terraform.yml@v2
    with:
        command_wrk_dir: './terraform'
        tf_command_fmt: 'terraform fmt'
    secrets:
        token: ${{ secrets.GITHUB_TOKEN }}
